apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokeapi
spec:
  selector:
    matchLabels:
      app: jokeapi
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: jokeapi
    spec:
      containers:
      - name: jokeapi
        image: oceacr.azurecr.us/jokeapi:0.0.0
        ports:
        - containerPort: 5000
        # env:       
        # - name: storagekey
        #   valueFrom:   
        #     secretKeyRef:
        #       name: storagekey
        #       key: storagekey       
---
apiVersion: v1
kind: Service
metadata:
    name: jokeapifront
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 5000
    selector:
        app: jokeapi